name: Build Package
description: Setting up environment and building Electron package

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13'

    - name: Install npm packages
      run: npm install

    - name: Build package
      run: npm run electron:build
