name: Build development package

on:
  # Runs every Monday at 1:00
  #schedule:
  #  - cron: '0 1 * * 1'
  workflow_dispatch:

env:
  RELEASE_UPLOAD_URL: "https://uploads.github.com/repos/thinreports/thinreports-section-editor/releases/59428964/assets{?name,label}"
  RELEASE_ID: 59428964

jobs:
  build-dev:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            package-ext: .dmg
          - os: ubuntu-latest
            package-ext: .AppImage
          - os: windows-latest
            package-ext: .exe

    steps:
      - uses: actions/checkout@v2

      - name: Build package
        uses: ./.github/actions/build-package

      - name: Prepare
        id: prepare
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const packagePath = fs.readdirSync('dist_electron').find(file => file.includes('${{ matrix.package-ext }}'));

            core.setOutput('PACKAGE_PATH', path.join('dist_electron', packagePath));
            core.setOutput('PACKAGE_NAME', path.basename(packagePath, '${{ matrix.package-ext }}'));

      - name: Deploy development build
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          release_id: ${{ env.RELEASE_ID }}
          asset_path: ${{ steps.prepare.outputs.PACKAGE_PATH }}
          asset_name: ${{ steps.prepare.outputs.PACKAGE_NAME }}-$$${{ matrix.package-ext }}
          asset_content_type: application/octet-stream
          max_releases: 1
