name: Build and release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            package-ext: .dmg
          - os: ubuntu-latest
            package-ext: .AppImage
          - os: windows-latest
            package-ext: .exe

    steps:
      - uses: actions/checkout@v4

      - name: Build package
        uses: ./.github/actions/build-package

      - name: Prepare package
        run: |
          mkdir package
          mv dist_electron/*${{ matrix.package-ext }} package/

      - name: Upload to artifact if not tagged
        uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags') }}
        with:
          name: ${{ matrix.os }}
          path: "package/*${{ matrix.package-ext }}"

      - name: Release if tagged
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: "package/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
