name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Run this build only on either pull request or push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Build and test with lint
      run: |
        npm install
        npm run test:lint
        npm run build
        npm run test:unit
